export const network: string = '{{ network }}'
export const stakingNftAddress: string = '{{ contracts.stakingNft.address }}'
export const registryAddress: string = '{{ contracts.registry.address }}'
export const decoderAddress: string = '{{ contracts.decoder.address }}'
export const decodeCheckpointSignerListAddress: string = '{{ contracts.decodeCheckpointSignerList.address }}'
